version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: register-payment-postgres
    environment:
      POSTGRES_DB: optica-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: optica123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: register-payment-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: optica123
      POSTGRES_DB: optica-db
      POSTGRES_SSL_MODE: disable
      QSTASH_CURRENT_SIGNING_KEY: ${QSTASH_CURRENT_SIGNING_KEY}
      QSTASH_NEXT_SIGNING_KEY: ${QSTASH_NEXT_SIGNING_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: