apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: payment-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: localhost:5000/optica/gateway-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: RABBITMQ_VHOST
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/gateway/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/gateway/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: payment-system
spec:
  selector:
    app: gateway-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
