apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: payment-system
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: b3B0aWNhMTIz
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
